name: Release Image

on:
  push:
    tags:
      - v*

jobs:

  deploy:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
      run: |
        IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Install yq
      run: |
        brew install --build-from-source yq@3

    - name: Clone manifest repository
      uses: actions/checkout@v2
      with:
        repository: po3rin/blog-k8s-resources
        token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}

    - name: Edit image tag
      env:
        GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
      run: | 
        ls -a
        yq --version
        IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
        yq w -i web/values.yaml container.image.tag $IMAGE_TAG
        yq eval 'container.image.tag = $IMAGE_TAG' web/values.yaml
        git diff
        git config user.email abctail30@gmail.com
        git config user.name po3rin
        git add .
        git commit -m "update tag ${IMAGE_TAG}"
        git push

